"""
Flask blueprint for initial setup wizard.
"""

import os
from pathlib import Path
from flask import Blueprint, render_template, request, redirect, url_for, flash
import requests

bp = Blueprint('setup', __name__, url_prefix='/setup')


def config_exists():
    """Check if .jira_environment file exists."""
    env_path = Path.cwd() / '.jira_environment'
    return env_path.exists()


def test_jira_connection(url, email, api_token):
    """Test if Jira credentials work.

    Returns:
        (success: bool, message: str, display_name: str)
    """
    try:
        url = url.rstrip('/')
        test_url = f"{url}/rest/api/3/myself"
        response = requests.get(
            test_url,
            auth=(email, api_token),
            timeout=10,
            verify=True
        )

        if response.status_code == 200:
            user_data = response.json()
            display_name = user_data.get('displayName', 'Unknown')
            return True, f"Successfully connected as: {display_name}", display_name
        else:
            return False, f"Connection failed: HTTP {response.status_code}", None
    except requests.exceptions.RequestException as e:
        return False, f"Connection error: {str(e)}", None


def get_boards(url, email, api_token):
    """Fetch available Jira boards.

    Returns:
        List of board dicts or empty list on error
    """
    try:
        url = url.rstrip('/')
        boards_url = f"{url}/rest/agile/1.0/board"
        response = requests.get(
            boards_url,
            auth=(email, api_token),
            params={"maxResults": 50},
            timeout=10,
            verify=True
        )

        if response.status_code == 200:
            return response.json().get('values', [])
        return []
    except Exception:
        return []


@bp.route('/', methods=['GET', 'POST'])
def index():
    """Setup wizard main page."""
    if request.method == 'GET':
        return render_template('setup/index.html')

    # POST: Save configuration
    try:
        # Get form data
        jira_url = request.form.get('jira_url', '').strip()
        email = request.form.get('email', '').strip()
        api_token = request.form.get('api_token', '').strip()
        board_id = request.form.get('board_id', '').strip()
        story_points = request.form.get('story_points', 'customfield_10024').strip()
        epic_link = request.form.get('epic_link', 'customfield_10031').strip()
        acceptance_criteria = request.form.get('acceptance_criteria', 'customfield_10140').strip()
        ssl_verify = request.form.get('ssl_verify', 'true').strip()

        # Validate required fields
        if not all([jira_url, email, api_token, board_id]):
            return render_template('setup/index.html',
                                   error="All required fields must be filled in.",
                                   form_data=request.form), 400

        # Create config file
        config_content = f"""# Jira Presentation Tool Configuration
# Generated by web setup wizard

# Jira Connection
JT_JIRA_URL={jira_url}
JT_JIRA_USERNAME={email}
JT_JIRA_PASSWORD={api_token}
JT_JIRA_BOARD={board_id}

# Custom Field IDs
JT_JIRA_FIELD_STORY_POINTS={story_points}
JT_JIRA_FIELD_EPIC_LINK={epic_link}
JT_JIRA_FIELD_ACCEPTANCE_CRITERIA={acceptance_criteria}

# SSL Verification
JT_SSL_VERIFY={ssl_verify}
"""

        env_path = Path.cwd() / '.jira_environment'
        with open(env_path, 'w') as f:
            f.write(config_content)

        # Set file permissions to 600 (owner read/write only) for security
        os.chmod(env_path, 0o600)

        return render_template('setup/success.html')

    except Exception as e:
        return render_template('setup/index.html',
                               error=f"Error saving configuration: {str(e)}",
                               form_data=request.form), 500


@bp.route('/test-connection', methods=['POST'])
def test_connection():
    """AJAX endpoint to test Jira connection."""
    jira_url = request.form.get('jira_url', '').strip()
    email = request.form.get('email', '').strip()
    api_token = request.form.get('api_token', '').strip()

    if not all([jira_url, email, api_token]):
        return {'success': False, 'message': 'Please fill in all connection fields'}, 400

    success, message, display_name = test_jira_connection(jira_url, email, api_token)

    if success:
        # Also fetch boards
        boards = get_boards(jira_url, email, api_token)
        return {
            'success': True,
            'message': message,
            'display_name': display_name,
            'boards': boards
        }
    else:
        return {
            'success': False,
            'message': message
        }
